services:
  nats-0:
    image: nats:2.10.16-alpine
    command: ["-c=/etc/nats/nats-server.conf", "--server_name=nats-0"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./data/nats-0:/data
      - ./nats-config:/etc/nats:ro
    security_opt:
      - label=disable
  nats-1:
    image: nats:2.10.16-alpine
    command: ["-c=/etc/nats/nats-server.conf", "--server_name=nats-1"]
    ports:
      - "4223:4222"
    volumes:
      - ./data/nats-1:/data
      - ./nats-config:/etc/nats:ro
    security_opt:
      - label=disable
  nats-2:
    image: nats:2.10.16-alpine
    command: ["-c=/etc/nats/nats-server.conf", "--server_name=nats-2"]
    ports:
      - "4224:4222"
    volumes:
      - ./data/nats-2:/data
      - ./nats-config:/etc/nats:ro
    security_opt:
      - label=disable
